[CSL 538] Add Support for Hidden Fields
Constructor-io/constructorio-client-swift pull request #123
Opened 2021-08-24 01:07 UTC by jjl014

#### Updates:
* Add support for hidden fields to Search/Browse/Autocomplete requests
* Add tests (all tests passing)

2021-08-24 21:54 UTC, rubikzube requested changes

2021-08-24 21:54 UTC, rubikzube commented on AutocompleteClient/FW/Logic/Request/CIOSearchQuery.swift
> +     let searchQuery = CIOSearchQuery(query: "red", filters: CIOQueryFilters(groupFilter: nil, facetFilters: facetFilters), page: 1, perPage: 30, section: "Products", hiddenFields: ["hiddenField1", "
Let's get a more descriptive example

2021-08-24 21:54 UTC, rubikzube commented on AutocompleteClient/FW/Logic/Request/CIOBrowseQuery.swift
> +     let browseQuery = CIOBrowseQuery(filterName: "group_id", filterValue: "Pantry", filters: CIOQueryFilters(groupFilter: nil, facetFilters: facetFilters), page: 1, perPage: 30, section: "Products",
Let's get a more descriptive example

2021-08-24 21:54 UTC, rubikzube commented on AutocompleteClient/FW/Logic/Request/CIOAutocompleteQuery.swift
> +     let autocompleteQuery = CIOAutocompleteQuery(query: "apple", numResults: 5, numResultsForSection: ["Products": 6, "Search Suggestions": 8], hiddenFields: ["hiddenField1", "hiddenField2"])
Let's get a more descriptive example

2021-08-24 21:54 UTC, rubikzube commented on AutocompleteClientTests/FW/Logic/Request/AutocompleteQueryRequestBuilderTests.swift
> +        let hiddenFields = ["hiddenField1", "hiddenField2"]
Let's get a more descriptive example

2021-08-25 16:39 UTC, jjl014 commented
Update: Hidden fields is not supported on the recommendations endpoint.

2021-08-31 13:25 UTC, rubikzube approved these changes

2021-08-31 13:31 UTC, rubikzube approved these changes

2021-08-31 13:31 UTC, merged